parameters:
#    ben_blog.example.class: Ben\BlogBundle\Example

services:
#    ben_blog.example:
#        class: %ben_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
